//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mi.Decompiler.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SampleInputFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SampleInputFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mi.Decompiler.Tests.SampleInputFiles", typeof(SampleInputFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] boxedoptarg {
            get {
                object obj = ResourceManager.GetObject("boxedoptarg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CallOverloadedMethod {
            get {
                object obj = ResourceManager.GetObject("CallOverloadedMethod", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Copyright (c) AlphaSierraPapa for the SharpDevelop Team
        ///// 
        ///// Permission is hereby granted, free of charge, to any person obtaining a copy of this
        ///// software and associated documentation files (the &quot;Software&quot;), to deal in the Software
        ///// without restriction, including without limitation the rights to use, copy, modify, merge,
        ///// publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons
        ///// to whom the Software is furnished to do so, subject to the following conditions:
        //// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CallOverloadedMethod_cs {
            get {
                return ResourceManager.GetString("CallOverloadedMethod_cs", resourceCulture);
            }
        }
        
        internal static byte[] CallOverloadedMethod_pdb {
            get {
                object obj = ResourceManager.GetObject("CallOverloadedMethod_pdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] catch_exe {
            get {
                object obj = ResourceManager.GetObject("catch_exe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CheckedUnchecked {
            get {
                object obj = ResourceManager.GetObject("CheckedUnchecked", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Copyright (c) AlphaSierraPapa for the SharpDevelop Team
        ///// 
        ///// Permission is hereby granted, free of charge, to any person obtaining a copy of this
        ///// software and associated documentation files (the &quot;Software&quot;), to deal in the Software
        ///// without restriction, including without limitation the rights to use, copy, modify, merge,
        ///// publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons
        ///// to whom the Software is furnished to do so, subject to the following conditions:
        //// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CheckedUnchecked_cs {
            get {
                return ResourceManager.GetString("CheckedUnchecked_cs", resourceCulture);
            }
        }
        
        internal static byte[] CheckedUnchecked_pdb {
            get {
                object obj = ResourceManager.GetObject("CheckedUnchecked_pdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] cppcli {
            get {
                object obj = ResourceManager.GetObject("cppcli", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CustomAttributes {
            get {
                object obj = ResourceManager.GetObject("CustomAttributes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Runtime.CompilerServices;
        ///
        ///[assembly: Foo (&quot;bingo&quot;)]
        ///
        ///[assembly: TypeForwardedTo (typeof (System.Diagnostics.DebuggableAttribute))]
        ///
        ///enum Bingo : short {
        ///	Fuel = 2,
        ///	Binga = 4,
        ///}
        ///
        ////*
        ///in System.Security.AccessControl
        ///
        ///	[Flags]
        ///	public enum AceFlags : byte {
        ///		None = 0,
        ///		ObjectInherit = 0x01,
        ///		ContainerInherit = 0x02,
        ///		NoPropagateInherit = 0x04,
        ///		InheritOnly = 0x08,
        ///		InheritanceFlags = ObjectInherit | ContainerInherit | NoPropagateInherit | Inh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CustomAttributes_cs {
            get {
                return ResourceManager.GetString("CustomAttributes_cs", resourceCulture);
            }
        }
        
        internal static byte[] CustomAttributes_pdb {
            get {
                object obj = ResourceManager.GetObject("CustomAttributes_pdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CustomAttributesAsm {
            get {
                object obj = ResourceManager.GetObject("CustomAttributesAsm", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CustomAttributesAsm_pdb {
            get {
                object obj = ResourceManager.GetObject("CustomAttributesAsm_pdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CustomShortCircuitOperators {
            get {
                object obj = ResourceManager.GetObject("CustomShortCircuitOperators", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CustomShortCircuitOperators_pdb {
            get {
                object obj = ResourceManager.GetObject("CustomShortCircuitOperators_pdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] decsec_att {
            get {
                object obj = ResourceManager.GetObject("decsec_att", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] decsec_xml {
            get {
                object obj = ResourceManager.GetObject("decsec_xml", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] decsec1_xml {
            get {
                object obj = ResourceManager.GetObject("decsec1_xml", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DelegateConstruction {
            get {
                object obj = ResourceManager.GetObject("DelegateConstruction", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Copyright (c) AlphaSierraPapa for the SharpDevelop Team
        ///// 
        ///// Permission is hereby granted, free of charge, to any person obtaining a copy of this
        ///// software and associated documentation files (the &quot;Software&quot;), to deal in the Software
        ///// without restriction, including without limitation the rights to use, copy, modify, merge,
        ///// publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons
        ///// to whom the Software is furnished to do so, subject to the following conditions:
        //// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DelegateConstruction_cs {
            get {
                return ResourceManager.GetString("DelegateConstruction_cs", resourceCulture);
            }
        }
        
        internal static byte[] DelegateConstruction_pdb {
            get {
                object obj = ResourceManager.GetObject("DelegateConstruction_pdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Events {
            get {
                object obj = ResourceManager.GetObject("Events", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///delegate void Pan (object sender, EventArgs args);
        ///
        ///abstract class Foo {
        ///
        ///	public abstract event Pan Bar;
        ///}
        ///.
        /// </summary>
        internal static string Events_cs {
            get {
                return ResourceManager.GetString("Events_cs", resourceCulture);
            }
        }
        
        internal static byte[] Events_pdb {
            get {
                object obj = ResourceManager.GetObject("Events_pdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ExceptionHandling {
            get {
                object obj = ResourceManager.GetObject("ExceptionHandling", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Copyright (c) AlphaSierraPapa for the SharpDevelop Team
        ///// 
        ///// Permission is hereby granted, free of charge, to any person obtaining a copy of this
        ///// software and associated documentation files (the &quot;Software&quot;), to deal in the Software
        ///// without restriction, including without limitation the rights to use, copy, modify, merge,
        ///// publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons
        ///// to whom the Software is furnished to do so, subject to the following conditions:
        //// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExceptionHandling_cs {
            get {
                return ResourceManager.GetString("ExceptionHandling_cs", resourceCulture);
            }
        }
        
        internal static byte[] ExceptionHandling_pdb {
            get {
                object obj = ResourceManager.GetObject("ExceptionHandling_pdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Fields {
            get {
                object obj = ResourceManager.GetObject("Fields", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Runtime.InteropServices;
        ///
        ///class Foo {
        ///	Bar bar;
        ///}
        ///
        ///class Bar {
        ///	volatile int oiseau;
        ///}
        ///
        ///class Baz {
        ///	bool @bool;
        ///	char @char;
        ///	sbyte @sbyte;
        ///	byte @byte;
        ///	short int16;
        ///	ushort uint16;
        ///	int int32;
        ///	uint uint32;
        ///	long int64;
        ///	ulong uint64;
        ///	float single;
        ///	double @double;
        ///	string @string;
        ///	object @object;
        ///}
        ///
        ///enum Pim {
        ///	Pam = 1,
        ///	Poum = 2,
        ///}
        ///
        ///class PanPan {
        ///
        ///	public const PanPan Peter = null;
        ///	public const string QQ = &quot;qq&quot;;
        ///	public const string nil = null;
        ///	public const object obj =  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Fields_cs {
            get {
                return ResourceManager.GetString("Fields_cs", resourceCulture);
            }
        }
        
        internal static byte[] Fields_pdb {
            get {
                object obj = ResourceManager.GetObject("Fields_pdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] fptr {
            get {
                object obj = ResourceManager.GetObject("fptr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Generics {
            get {
                object obj = ResourceManager.GetObject("Generics", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Copyright (c) AlphaSierraPapa for the SharpDevelop Team
        ///// 
        ///// Permission is hereby granted, free of charge, to any person obtaining a copy of this
        ///// software and associated documentation files (the &quot;Software&quot;), to deal in the Software
        ///// without restriction, including without limitation the rights to use, copy, modify, merge,
        ///// publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons
        ///// to whom the Software is furnished to do so, subject to the following conditions:
        //// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Generics_cs {
            get {
                return ResourceManager.GetString("Generics_cs", resourceCulture);
            }
        }
        
        internal static byte[] Generics_pdb {
            get {
                object obj = ResourceManager.GetObject("Generics_pdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] GenericsAsm {
            get {
                object obj = ResourceManager.GetObject("GenericsAsm", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] GenericsAsm_pdb {
            get {
                object obj = ResourceManager.GetObject("GenericsAsm_pdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] gifaceref {
            get {
                object obj = ResourceManager.GetObject("gifaceref", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] hello {
            get {
                object obj = ResourceManager.GetObject("hello", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] hello_anycpu {
            get {
                object obj = ResourceManager.GetObject("hello_anycpu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] hello_ia64 {
            get {
                object obj = ResourceManager.GetObject("hello_ia64", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] hello_x64 {
            get {
                object obj = ResourceManager.GetObject("hello_x64", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] hello_x86 {
            get {
                object obj = ResourceManager.GetObject("hello_x86", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] hello1 {
            get {
                object obj = ResourceManager.GetObject("hello1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] hellow {
            get {
                object obj = ResourceManager.GetObject("hellow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] IncrementDecrement {
            get {
                object obj = ResourceManager.GetObject("IncrementDecrement", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Copyright (c) AlphaSierraPapa for the SharpDevelop Team
        ///// 
        ///// Permission is hereby granted, free of charge, to any person obtaining a copy of this
        ///// software and associated documentation files (the &quot;Software&quot;), to deal in the Software
        ///// without restriction, including without limitation the rights to use, copy, modify, merge,
        ///// publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons
        ///// to whom the Software is furnished to do so, subject to the following conditions:
        //// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IncrementDecrement_cs {
            get {
                return ResourceManager.GetString("IncrementDecrement_cs", resourceCulture);
            }
        }
        
        internal static byte[] IncrementDecrement_pdb {
            get {
                object obj = ResourceManager.GetObject("IncrementDecrement_pdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] InitializerTests {
            get {
                object obj = ResourceManager.GetObject("InitializerTests", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Copyright (c) AlphaSierraPapa for the SharpDevelop Team
        ///// 
        ///// Permission is hereby granted, free of charge, to any person obtaining a copy of this
        ///// software and associated documentation files (the &quot;Software&quot;), to deal in the Software
        ///// without restriction, including without limitation the rights to use, copy, modify, merge,
        ///// publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons
        ///// to whom the Software is furnished to do so, subject to the following conditions:
        //// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InitializerTests_cs {
            get {
                return ResourceManager.GetString("InitializerTests_cs", resourceCulture);
            }
        }
        
        internal static byte[] InitializerTests_pdb {
            get {
                object obj = ResourceManager.GetObject("InitializerTests_pdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Interfaces {
            get {
                object obj = ResourceManager.GetObject("Interfaces", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///interface IFoo {}
        ///interface IBar : IFoo  {}
        ///
        ///abstract class Bar : IBar {}
        ///
        ///interface IBingo {
        ///	void Foo ();
        ///	void Bar ();
        ///}
        ///
        ///class Bingo : IBingo {
        ///
        ///	void IBingo.Foo ()
        ///	{
        ///	}
        ///
        ///	void IBingo.Bar ()
        ///	{
        ///	}
        ///}
        ///.
        /// </summary>
        internal static string Interfaces_cs {
            get {
                return ResourceManager.GetString("Interfaces_cs", resourceCulture);
            }
        }
        
        internal static byte[] Interfaces_pdb {
            get {
                object obj = ResourceManager.GetObject("Interfaces_pdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] iterator {
            get {
                object obj = ResourceManager.GetObject("iterator", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Layouts {
            get {
                object obj = ResourceManager.GetObject("Layouts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Runtime.InteropServices;
        ///
        ///[StructLayout (LayoutKind.Explicit, Size = 16)]
        ///public struct Foo {
        ///	[FieldOffset (0)] public ushort Bar;
        ///	[FieldOffset (2)] public ushort Baz;
        ///	[FieldOffset (4)] public uint Gazonk;
        ///}
        ///
        ///class Babar {
        ///}
        ///
        ///class Locke {
        ///	public int [] integers = new int [] { 1, 2, 3, 4 };
        ///}
        ///.
        /// </summary>
        internal static string Layouts_cs {
            get {
                return ResourceManager.GetString("Layouts_cs", resourceCulture);
            }
        }
        
        internal static byte[] Layouts_pdb {
            get {
                object obj = ResourceManager.GetObject("Layouts_pdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] libhello {
            get {
                object obj = ResourceManager.GetObject("libhello", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] libres {
            get {
                object obj = ResourceManager.GetObject("libres", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Loops {
            get {
                object obj = ResourceManager.GetObject("Loops", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Copyright (c) AlphaSierraPapa for the SharpDevelop Team
        ///// 
        ///// Permission is hereby granted, free of charge, to any person obtaining a copy of this
        ///// software and associated documentation files (the &quot;Software&quot;), to deal in the Software
        ///// without restriction, including without limitation the rights to use, copy, modify, merge,
        ///// publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons
        ///// to whom the Software is furnished to do so, subject to the following conditions:
        //// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Loops_cs {
            get {
                return ResourceManager.GetString("Loops_cs", resourceCulture);
            }
        }
        
        internal static byte[] Loops_pdb {
            get {
                object obj = ResourceManager.GetObject("Loops_pdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] marshal {
            get {
                object obj = ResourceManager.GetObject("marshal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Methods {
            get {
                object obj = ResourceManager.GetObject("Methods", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Runtime.InteropServices;
        ///
        ///abstract class Foo {
        ///	public abstract void Bar (int a);
        ///}
        ///
        ///class Bar {
        ///
        ///	[DllImport (&quot;foo.dll&quot;)]
        ///	public extern static void Pan ([MarshalAs (UnmanagedType.I4)] int i);
        ///}
        ///
        ///public class Baz {
        ///
        ///	public void PrintAnswer ()
        ///	{
        ///		Console.WriteLine (&quot;answer: {0}&quot;, 42);
        ///	}
        ///}
        ///
        ///.
        /// </summary>
        internal static string Methods_cs {
            get {
                return ResourceManager.GetString("Methods_cs", resourceCulture);
            }
        }
        
        internal static byte[] Methods_pdb {
            get {
                object obj = ResourceManager.GetObject("Methods_pdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] mma {
            get {
                object obj = ResourceManager.GetObject("mma", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] moda {
            get {
                object obj = ResourceManager.GetObject("moda", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] modb {
            get {
                object obj = ResourceManager.GetObject("modb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] mscorlib {
            get {
                object obj = ResourceManager.GetObject("mscorlib", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MultidimensionalArray {
            get {
                object obj = ResourceManager.GetObject("MultidimensionalArray", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Copyright (c) AlphaSierraPapa for the SharpDevelop Team
        ///// 
        ///// Permission is hereby granted, free of charge, to any person obtaining a copy of this
        ///// software and associated documentation files (the &quot;Software&quot;), to deal in the Software
        ///// without restriction, including without limitation the rights to use, copy, modify, merge,
        ///// publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons
        ///// to whom the Software is furnished to do so, subject to the following conditions:
        //// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MultidimensionalArray_cs {
            get {
                return ResourceManager.GetString("MultidimensionalArray_cs", resourceCulture);
            }
        }
        
        internal static byte[] MultidimensionalArray_pdb {
            get {
                object obj = ResourceManager.GetObject("MultidimensionalArray_pdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] NestedTypes {
            get {
                object obj = ResourceManager.GetObject("NestedTypes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class Foo {
        ///	class Bar {
        ///		class Baz {
        ///		}
        ///	}
        ///}
        ///
        ///class Bingo {
        ///	public class Fuel {
        ///	}
        ///
        ///	public static Fuel GetFuel ()
        ///	{
        ///		return null;
        ///	}
        ///}
        ///.
        /// </summary>
        internal static string NestedTypes_cs {
            get {
                return ResourceManager.GetString("NestedTypes_cs", resourceCulture);
            }
        }
        
        internal static byte[] NestedTypes_pdb {
            get {
                object obj = ResourceManager.GetObject("NestedTypes_pdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] noblob {
            get {
                object obj = ResourceManager.GetObject("noblob", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PInvoke {
            get {
                object obj = ResourceManager.GetObject("PInvoke", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Copyright (c) 2011 AlphaSierraPapa for the SharpDevelop Team
        ///// 
        ///// Permission is hereby granted, free of charge, to any person obtaining a copy of this
        ///// software and associated documentation files (the &quot;Software&quot;), to deal in the Software
        ///// without restriction, including without limitation the rights to use, copy, modify, merge,
        ///// publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons
        ///// to whom the Software is furnished to do so, subject to the following conditio [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PInvoke_cs {
            get {
                return ResourceManager.GetString("PInvoke_cs", resourceCulture);
            }
        }
        
        internal static byte[] pinvoke_exe {
            get {
                object obj = ResourceManager.GetObject("pinvoke_exe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PInvoke_pdb {
            get {
                object obj = ResourceManager.GetObject("PInvoke_pdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Properties {
            get {
                object obj = ResourceManager.GetObject("Properties", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///abstract class Foo {
        ///
        ///	public abstract int Bar { get; }
        ///	public abstract string Baz { get; set; }
        ///	public abstract string Gazonk { set; }
        ///}
        ///
        ///abstract class Bar {
        ///
        ///	public abstract Foo this [int a, string s] { set; }
        ///}
        ///
        ///class Baz {
        ///
        ///	public string Bingo { get; set; }
        ///}
        ///.
        /// </summary>
        internal static string Properties_cs {
            get {
                return ResourceManager.GetString("Properties_cs", resourceCulture);
            }
        }
        
        internal static byte[] Properties_pdb {
            get {
                object obj = ResourceManager.GetObject("Properties_pdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PropertiesAndEvents {
            get {
                object obj = ResourceManager.GetObject("PropertiesAndEvents", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Copyright (c) AlphaSierraPapa for the SharpDevelop Team
        ///// 
        ///// Permission is hereby granted, free of charge, to any person obtaining a copy of this
        ///// software and associated documentation files (the &quot;Software&quot;), to deal in the Software
        ///// without restriction, including without limitation the rights to use, copy, modify, merge,
        ///// publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons
        ///// to whom the Software is furnished to do so, subject to the following conditions:
        //// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PropertiesAndEvents_cs {
            get {
                return ResourceManager.GetString("PropertiesAndEvents_cs", resourceCulture);
            }
        }
        
        internal static byte[] PropertiesAndEvents_pdb {
            get {
                object obj = ResourceManager.GetObject("PropertiesAndEvents_pdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] QueryExpressions {
            get {
                object obj = ResourceManager.GetObject("QueryExpressions", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Copyright (c) AlphaSierraPapa for the SharpDevelop Team
        ///// 
        ///// Permission is hereby granted, free of charge, to any person obtaining a copy of this
        ///// software and associated documentation files (the &quot;Software&quot;), to deal in the Software
        ///// without restriction, including without limitation the rights to use, copy, modify, merge,
        ///// publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons
        ///// to whom the Software is furnished to do so, subject to the following conditions:
        //// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QueryExpressions_cs {
            get {
                return ResourceManager.GetString("QueryExpressions_cs", resourceCulture);
            }
        }
        
        internal static byte[] QueryExpressions_pdb {
            get {
                object obj = ResourceManager.GetObject("QueryExpressions_pdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] S_AssemblyCustomAttribute {
            get {
                object obj = ResourceManager.GetObject("S_AssemblyCustomAttribute", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Copyright (c) AlphaSierraPapa for the SharpDevelop Team (for details please see \doc\copyright.txt)
        ///// This code is distributed under MIT X11 license (for details please see \doc\license.txt)
        ///
        ///using System;
        ///
        ///[assembly: CLSCompliant(false)].
        /// </summary>
        internal static string S_AssemblyCustomAttribute_cs {
            get {
                return ResourceManager.GetString("S_AssemblyCustomAttribute_cs", resourceCulture);
            }
        }
        
        internal static byte[] S_AssemblyCustomAttribute_pdb {
            get {
                object obj = ResourceManager.GetObject("S_AssemblyCustomAttribute_pdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] S_CustomAttributes {
            get {
                object obj = ResourceManager.GetObject("S_CustomAttributes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Copyright (c) AlphaSierraPapa for the SharpDevelop Team (for details please see \doc\copyright.txt)
        ///// This code is distributed under MIT X11 license (for details please see \doc\license.txt)
        ///
        ///using System;
        ///
        ///namespace aa
        ///{
        ///	public static class CustomAttributes
        ///	{
        ///		[Flags]
        ///		public enum EnumWithFlag
        ///		{
        ///			All = 15,
        ///			None = 0,
        ///			Item1 = 1,
        ///			Item2 = 2,
        ///			Item3 = 4,
        ///			Item4 = 8
        ///		}
        ///		[AttributeUsage(AttributeTargets.All)]
        ///		public class MyAttribute : Attribute
        ///		{
        ///			public MyAttribute(object val)
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string S_CustomAttributes_cs {
            get {
                return ResourceManager.GetString("S_CustomAttributes_cs", resourceCulture);
            }
        }
        
        internal static byte[] S_CustomAttributes_pdb {
            get {
                object obj = ResourceManager.GetObject("S_CustomAttributes_pdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] S_CustomAttributeSamples {
            get {
                object obj = ResourceManager.GetObject("S_CustomAttributeSamples", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Copyright (c) AlphaSierraPapa for the SharpDevelop Team (for details please see \doc\copyright.txt)
        ///// This code is distributed under MIT X11 license (for details please see \doc\license.txt)
        ///
        /////$CS
        ///using System;
        /////$CE
        ///
        /////$$ TargetModule (ignored)
        /////[module: CLSCompliantAttribute(false)]
        /////$$ ParameterlessAttributeUsage
        ///namespace ParameterLessAttributeUsage
        ///{
        ///	[Flags]
        ///	public enum EnumWithFlagsAttribute
        ///	{
        ///		None = 0
        ///	}
        ///}
        /////$$ AttributeWithEnumArgument
        ///namespace AttributeWithEnumArgument
        ///{
        ///	[AttributeUsa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string S_CustomAttributeSamples_cs {
            get {
                return ResourceManager.GetString("S_CustomAttributeSamples_cs", resourceCulture);
            }
        }
        
        internal static byte[] S_CustomAttributeSamples_pdb {
            get {
                object obj = ResourceManager.GetObject("S_CustomAttributeSamples_pdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] S_EnumSamples {
            get {
                object obj = ResourceManager.GetObject("S_EnumSamples", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Copyright (c) AlphaSierraPapa for the SharpDevelop Team (for details please see \doc\copyright.txt)
        ///// This code is distributed under MIT X11 license (for details please see \doc\license.txt)
        ///
        /////$CS
        ///using System;
        /////$CE
        ///
        ///public static class S_EnumSamples
        ///{
        ///
        ///    //$$ SingleValue
        ///    public class TS_SingleValue
        ///    {
        ///        public AttributeTargets Method()
        ///        {
        ///            return AttributeTargets.Class;
        ///        }
        ///    }
        ///    //$$ TwoValuesOr
        ///    public class TS_TwoValuesOr
        ///    {
        ///        public Attribute [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string S_EnumSamples_cs {
            get {
                return ResourceManager.GetString("S_EnumSamples_cs", resourceCulture);
            }
        }
        
        internal static byte[] S_EnumSamples_pdb {
            get {
                object obj = ResourceManager.GetObject("S_EnumSamples_pdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] S_TypeDeclarations {
            get {
                object obj = ResourceManager.GetObject("S_TypeDeclarations", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace ClassMultiInterface
        ///{
        ///	public interface IA
        ///	{
        ///	}
        ///	public interface IA2 : IA
        ///	{
        ///	}
        ///	public interface IB
        ///	{
        ///	}
        ///	public class C : IA2, IB
        ///	{
        ///	}
        ///}
        ///.
        /// </summary>
        internal static string S_TypeDeclarations_cs {
            get {
                return ResourceManager.GetString("S_TypeDeclarations_cs", resourceCulture);
            }
        }
        
        internal static byte[] S_TypeDeclarations_pdb {
            get {
                object obj = ResourceManager.GetObject("S_TypeDeclarations_pdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] S_TypeMemberDeclarations {
            get {
                object obj = ResourceManager.GetObject("S_TypeMemberDeclarations", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Copyright (c) AlphaSierraPapa for the SharpDevelop Team (for details please see \doc\copyright.txt)
        ///// This code is distributed under MIT X11 license (for details please see \doc\license.txt)
        ///
        /////$CS
        ///using System;
        /////$CE
        ///
        /////$$ IndexerWithGetOnly
        ///namespace IndexerWithGetOnly
        ///{
        ///	public class MyClass
        ///	{
        ///		public int this[int i]
        ///		{
        ///			get
        ///			{
        ///				return i;
        ///			}
        ///		}
        ///	}
        ///}
        /////$$ IndexerWithSetOnly
        ///namespace IndexerWithSetOnly
        ///{
        ///	public class MyClass
        ///	{
        ///		public int this[int i]
        ///		{
        ///			set
        ///			{
        ///			}
        ///		}
        ///	}
        ///}
        /////$$  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string S_TypeMemberDeclarations_cs {
            get {
                return ResourceManager.GetString("S_TypeMemberDeclarations_cs", resourceCulture);
            }
        }
        
        internal static byte[] S_TypeMemberDeclarations_pdb {
            get {
                object obj = ResourceManager.GetObject("S_TypeMemberDeclarations_pdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Switch {
            get {
                object obj = ResourceManager.GetObject("Switch", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Copyright (c) AlphaSierraPapa for the SharpDevelop Team
        ///// 
        ///// Permission is hereby granted, free of charge, to any person obtaining a copy of this
        ///// software and associated documentation files (the &quot;Software&quot;), to deal in the Software
        ///// without restriction, including without limitation the rights to use, copy, modify, merge,
        ///// publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons
        ///// to whom the Software is furnished to do so, subject to the following conditions:
        //// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Switch_cs {
            get {
                return ResourceManager.GetString("Switch_cs", resourceCulture);
            }
        }
        
        internal static byte[] switch_dll {
            get {
                object obj = ResourceManager.GetObject("switch_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Switch_pdb {
            get {
                object obj = ResourceManager.GetObject("Switch_pdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] system {
            get {
                object obj = ResourceManager.GetObject("system", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SystemCore {
            get {
                object obj = ResourceManager.GetObject("SystemCore", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cecil ftw!
        ///.
        /// </summary>
        internal static string text_file {
            get {
                return ResourceManager.GetString("text_file", resourceCulture);
            }
        }
        
        internal static byte[] UndocumentedExpressions {
            get {
                object obj = ResourceManager.GetObject("UndocumentedExpressions", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Copyright (c) AlphaSierraPapa for the SharpDevelop Team
        ///// 
        ///// Permission is hereby granted, free of charge, to any person obtaining a copy of this
        ///// software and associated documentation files (the &quot;Software&quot;), to deal in the Software
        ///// without restriction, including without limitation the rights to use, copy, modify, merge,
        ///// publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons
        ///// to whom the Software is furnished to do so, subject to the following conditions:
        //// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UndocumentedExpressions_cs {
            get {
                return ResourceManager.GetString("UndocumentedExpressions_cs", resourceCulture);
            }
        }
        
        internal static byte[] UndocumentedExpressions_pdb {
            get {
                object obj = ResourceManager.GetObject("UndocumentedExpressions_pdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] UnsafeCode {
            get {
                object obj = ResourceManager.GetObject("UnsafeCode", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Copyright (c) AlphaSierraPapa for the SharpDevelop Team
        ///// 
        ///// Permission is hereby granted, free of charge, to any person obtaining a copy of this
        ///// software and associated documentation files (the &quot;Software&quot;), to deal in the Software
        ///// without restriction, including without limitation the rights to use, copy, modify, merge,
        ///// publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons
        ///// to whom the Software is furnished to do so, subject to the following conditions:
        //// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UnsafeCode_cs {
            get {
                return ResourceManager.GetString("UnsafeCode_cs", resourceCulture);
            }
        }
        
        internal static byte[] UnsafeCode_pdb {
            get {
                object obj = ResourceManager.GetObject("UnsafeCode_pdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ValueTypes {
            get {
                object obj = ResourceManager.GetObject("ValueTypes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Copyright (c) AlphaSierraPapa for the SharpDevelop Team
        ///// 
        ///// Permission is hereby granted, free of charge, to any person obtaining a copy of this
        ///// software and associated documentation files (the &quot;Software&quot;), to deal in the Software
        ///// without restriction, including without limitation the rights to use, copy, modify, merge,
        ///// publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons
        ///// to whom the Software is furnished to do so, subject to the following conditions:
        //// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ValueTypes_cs {
            get {
                return ResourceManager.GetString("ValueTypes_cs", resourceCulture);
            }
        }
        
        internal static byte[] ValueTypes_pdb {
            get {
                object obj = ResourceManager.GetObject("ValueTypes_pdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] varargs {
            get {
                object obj = ResourceManager.GetObject("varargs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] YieldReturn {
            get {
                object obj = ResourceManager.GetObject("YieldReturn", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Copyright (c) AlphaSierraPapa for the SharpDevelop Team
        ///// 
        ///// Permission is hereby granted, free of charge, to any person obtaining a copy of this
        ///// software and associated documentation files (the &quot;Software&quot;), to deal in the Software
        ///// without restriction, including without limitation the rights to use, copy, modify, merge,
        ///// publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons
        ///// to whom the Software is furnished to do so, subject to the following conditions:
        //// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string YieldReturn_cs {
            get {
                return ResourceManager.GetString("YieldReturn_cs", resourceCulture);
            }
        }
        
        internal static byte[] YieldReturn_pdb {
            get {
                object obj = ResourceManager.GetObject("YieldReturn_pdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
