//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.431
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mi.Decompiler.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SampleInputFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SampleInputFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mi.Decompiler.Tests.SampleInputFiles", typeof(SampleInputFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] CallOverloadedMethod {
            get {
                object obj = ResourceManager.GetObject("CallOverloadedMethod", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CallOverloadedMethod_pdb {
            get {
                object obj = ResourceManager.GetObject("CallOverloadedMethod_pdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CheckedUnchecked {
            get {
                object obj = ResourceManager.GetObject("CheckedUnchecked", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CheckedUnchecked_pdb {
            get {
                object obj = ResourceManager.GetObject("CheckedUnchecked_pdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CustomAttributes {
            get {
                object obj = ResourceManager.GetObject("CustomAttributes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CustomAttributes_pdb {
            get {
                object obj = ResourceManager.GetObject("CustomAttributes_pdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DelegateConstruction {
            get {
                object obj = ResourceManager.GetObject("DelegateConstruction", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DelegateConstruction_pdb {
            get {
                object obj = ResourceManager.GetObject("DelegateConstruction_pdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ExceptionHandling {
            get {
                object obj = ResourceManager.GetObject("ExceptionHandling", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ExceptionHandling_pdb {
            get {
                object obj = ResourceManager.GetObject("ExceptionHandling_pdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] IncrementDecrement {
            get {
                object obj = ResourceManager.GetObject("IncrementDecrement", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] IncrementDecrement_pdb {
            get {
                object obj = ResourceManager.GetObject("IncrementDecrement_pdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] InitializerTests {
            get {
                object obj = ResourceManager.GetObject("InitializerTests", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] InitializerTests_pdb {
            get {
                object obj = ResourceManager.GetObject("InitializerTests_pdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Loops {
            get {
                object obj = ResourceManager.GetObject("Loops", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Loops1 {
            get {
                object obj = ResourceManager.GetObject("Loops1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] mscorlib {
            get {
                object obj = ResourceManager.GetObject("mscorlib", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MultidimensionalArray {
            get {
                object obj = ResourceManager.GetObject("MultidimensionalArray", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MultidimensionalArray_pdb {
            get {
                object obj = ResourceManager.GetObject("MultidimensionalArray_pdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PropertiesAndEvents {
            get {
                object obj = ResourceManager.GetObject("PropertiesAndEvents", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PropertiesAndEvents_pdb {
            get {
                object obj = ResourceManager.GetObject("PropertiesAndEvents_pdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] QueryExpressions {
            get {
                object obj = ResourceManager.GetObject("QueryExpressions", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] QueryExpressions_pdb {
            get {
                object obj = ResourceManager.GetObject("QueryExpressions_pdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Switch {
            get {
                object obj = ResourceManager.GetObject("Switch", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Switch_pdb {
            get {
                object obj = ResourceManager.GetObject("Switch_pdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] system {
            get {
                object obj = ResourceManager.GetObject("system", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] System_Core {
            get {
                object obj = ResourceManager.GetObject("System_Core", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] UndocumentedExpressions {
            get {
                object obj = ResourceManager.GetObject("UndocumentedExpressions", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] UndocumentedExpressions_pdb {
            get {
                object obj = ResourceManager.GetObject("UndocumentedExpressions_pdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] UnsafeCode {
            get {
                object obj = ResourceManager.GetObject("UnsafeCode", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] UnsafeCode_pdb {
            get {
                object obj = ResourceManager.GetObject("UnsafeCode_pdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ValueTypes {
            get {
                object obj = ResourceManager.GetObject("ValueTypes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ValueTypes_pdb {
            get {
                object obj = ResourceManager.GetObject("ValueTypes_pdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] YieldReturn {
            get {
                object obj = ResourceManager.GetObject("YieldReturn", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] YieldReturn_pdb {
            get {
                object obj = ResourceManager.GetObject("YieldReturn_pdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
